/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 1-Monthon 2026 18班バックエンド
 * OpenAPI spec version: 0.1.0
 */
export interface Beat {
  endsAtMs: number
  startsAtMs: number
}

export interface Phrase {
  endsAtMs: number
  startsAtMs: number
  text: string
}

export interface Segment {
  endsAtMs: number
  isChorus: boolean
  startsAtMs: number
}

export interface CompleteSongData {
  artist: string
  beats: Beat[]
  durationMs: number
  phrases: Phrase[]
  segments: Segment[]
  title: string
}

export interface CreateSongRequest {
  artist: string
  lyrics: string
  title: string
  url: string
}

export interface FetchedPhrase {
  /** @minimum 0 */
  charCount: number
  endsAtMs: number
  startsAtMs: number
  text: string
}

export interface FetchedIncompleteSongData {
  beats: Beat[]
  durationMs: number
  phrases: FetchedPhrase[]
  segments: Segment[]
}

export type FetchedSongData =
  | CompleteSongData & {
    type: "complete"
  }
  | FetchedIncompleteSongData & {
    type: "incomplete"
  }

export interface IncompleteSongData {
  beats: Beat[]
  durationMs: number
  segments: Segment[]
}

export type SongData =
  | CompleteSongData & {
    type: "complete"
  }
  | IncompleteSongData & {
    type: "incomplete"
  }

export type GetSongByPublicUrlParams = {
  /**
   * [TextAlive](https://textalive.jp/songs)に登録されている曲のURL
   */
  url: string
}
