/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 1-Monthon 2026 18班バックエンド
 * OpenAPI spec version: 0.1.0
 */
export interface Beat {
  endsAtMs: number
  startsAtMs: number
}

/**
 * Response containing the information required for clients to establish a
 * WebTransport connection.
 *
 * The server uses a self-signed certificate regenerated on every process
 * start; browsers must pass its SHA-256 digest as `serverCertificateHashes`
 * when connecting.
 */
export interface CertificateHashResponse {
  /**
   * SHA-256 digest of the self-signed certificate, lowercase hex (64 chars).
   *
   * Decode into 32 raw bytes and pass them as
   * `{ algorithm: "sha-256", value: <ArrayBuffer> }` in the browser's
   * `serverCertificateHashes`.
   */
  certificateHash: string
  /**
   * UDP port the WebTransport server listens on.
   * @minimum 0
   */
  port: number
}

export interface Phrase {
  endsAtMs: number
  startsAtMs: number
  text: string
}

export interface Segment {
  endsAtMs: number
  isChorus: boolean
  startsAtMs: number
}

export interface CompleteSongData {
  artist: string
  beats: Beat[]
  durationMs: number
  phrases: Phrase[]
  segments: Segment[]
  title: string
}

export interface CreateRoomRequest {
  songUrl: string
}

export interface CreateRoomResponse {
  hostToken: string
  roomId: string
}

export interface CreateSongRequest {
  artist: string
  lyrics: string
  lyricsJsonUrl: string
  songUrl: string
  title: string
}

export interface FetchedIncompleteSongData {
  beats: Beat[]
  durationMs: number
  segments: Segment[]
}

export type FetchedSongData =
  | CompleteSongData & {
    type: "complete"
  }
  | FetchedIncompleteSongData & {
    type: "incomplete"
  }

export interface IncompleteSongData {
  beats: Beat[]
  durationMs: number
  segments: Segment[]
}

export type SongData =
  | CompleteSongData & {
    type: "complete"
  }
  | IncompleteSongData & {
    type: "incomplete"
  }

export type GetSongByUrlParams = {
  /**
   * [TextAlive](https://textalive.jp/songs)に登録されている曲のURL
   */
  url: string
}
